namespace Audio.Chunks.Types.HIRC;

public enum ActionType
{
    None,
    Stop,
    Pause,
    Resume,
    Play,
    PlayAndContinue,
    Mute,
    Unmute,
    SetPitch,
    ResetPitch,
    SetVolume,
    ResetVolume,
    SetBusVolume,
    ResetBusVolume,
    SetLowPassFilter,
    ResetLowPassFilter,
    UseState,
    UnuseState,
    SetState,
    SetGameParameter,
    ResetGameParameter,
    StopEvent,
    PauseEvent,
    ResumeEvent,
    Duck,
    SetSwitch,
    SetBypassEffect,
    ResetBypassEffect,
    Break,
    Trigger,
    Seek,
    Release,
    SetHighPassFilter,
    PlayEvent,
    ResetPlaylist,
    ResetHighPassFilter = 0x30,
}